spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    url: jdbc:mysql://localhost:3306/form_team_talent?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  application:
    name: form-team-talent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8080

wx:
  appId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  appSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  getOpenIdUrl: https://api.weixin.qq.com/sns/jscode2session

auth:
  jwt:
    secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    expire: xxxxxxxxxxxxxxxxxxxxx