spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 658766
    url: jdbc:mysql://localhost:3306/form_team_talent?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  application:
    name: form-team-talent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8080

wx:
  appId: wx2321b1cd8170b56e
  appSecret: 4fec11577d828eb6f03a5ef06a1b7eca
  getOpenIdUrl: https://api.weixin.qq.com/sns/jscode2session

auth:
  jwt:
    secret: xdudasfjlsaj2139dasjwerjawr213jfsadafd
    expire: 432000